### ISSUE TITLE
remake respawn ticket system from FF2 subplugin for VSH2

### ISSUE THREAD

**Issue by assyrianic** [VSH2-Devs/Vs-Saxton-Hale-2#16]
apparently, the original creator of vsh and ff2 made a respawn ticket subplugin which was created to address the apparent issues of people getting bored because they died very quickly and had to wait for a new round.

I was thinking of adding that as an internal feature managed by the gamemode manager and enabled by cvar.

as far as I know, the mechanics for the respawn ticket was that RED team had a limited number of respawns that was shared by everybody and each person could stake a claim to the tickets unless they were all used up.

Each claimed "ticket" was then called on a timer to respawn the ticket claimers all at one time.

https://forums.alliedmods.net/showthread.php?t=257728

**Comment by Starblaster64** [comment]
Wow, I never even remembered that existing.

**Comment by assyrianic** [comment]
it was discreetly released in 2016

**Comment by assyrianic** [comment]
adding notes here for how I would implement it.

Ticket system will just utilize the "lives" system that VSH2 has built in already but it's currently unused so this respawn ticket thing will actually put it to use.

red team will get a limited amount of respawn tickets that's shared for the entire team and each respawn using the ticket will increase the current boss' health by a certain amount as well as divide and increase for multibosses (living bosses of course, one living boss will get the full amount as if it was a one boss round).

I'll add cvars to enable respawn tickets, the amount of respawn tickets for red team, and the amount of health to give back to the boss when someone respawns using a ticket.

**Comment by assyrianic** [comment]
not actually in progress as there doesn't seem to be demand for this unless you want it lol

**Comment by kevyonan** [comment]
Closing this because this can be done through the VSH2 API as a custom plugin.
