### ISSUE TITLE
Shortstop alt-fire instantly kills

### ISSUE THREAD

**Issue by x3m77rus** [VSH2-Devs/Vs-Saxton-Hale-2#50]
If boss doing taunt, scout can instantly kill him with Shortstop alt-fire.

1.5.1 Beta

**Comment by assyrianic** [comment]
wait, REALLY? lolol! I gotta test this out for myself holy moly.

**Comment by assyrianic** [comment]
i looked into it more, it doesn't activate or fire OnTakeDamage or the PlayerHurt event. All I know is that when it occurs, it says that the victim suicided in the console... Could this possibly be a TF2 related bug?

**Comment by x3m77rus** [comment]
I have no idea what can cause this, maybe just blacklist Shortstop until something become clear?
Also found a few more bugs:
- If you disguise as your teammate and boss trigger your feign death, teammate become zombie
- All damage dealt to zombies decreases boss health

**Comment by assyrianic** [comment]
the 2nd bug is not a bug but intentional. If the zombies don't decrease boss health, then any plague doctor player can just kill people and afk somewhere while the minions do all the work.

1st part is definitely needed for fixing.

**Comment by assyrianic** [comment]
"If you disguise as your teammate and boss trigger your feign death, teammate become zombie"

fukken FIXED :P

**Comment by assyrianic** [comment]
unfortunately, I cannot get the shortstop glitch fixed.
I've fixed up every other glitch except that one because it's very odd. It doesn't do any damage and when you execute this glitch, all it says is that the player suicided....

**Comment by Starblaster64** [comment]
Shortstop deals 1 damage when using the shove. The damage owner is not set to the Shortstop user, I assumed it was set to the world, but perhaps it's actually set to the victim instead.
Hopefully Valve fixes the 1 damage to be dealt by the Shortstop owner, thus solving this issue.

**Comment by x3m77rus** [comment]
Wiki says, victim won't get this 1 damage immediately, so even if problem in owner, this must happen when boss get hurt. But this happening immediately.

**Comment by x3m77rus** [comment]
A little more information. On my server I use taunt crits plugin, and if you get crits from taunt and damage the boss while he is doing taunt too it will damage him around 30000 hp. Any other ways become crit boosted working as expected.
So I'm think when boss get cond taunting something goes wrong, because scout's Shortstop bug also working only when boss in taunting cond.

**Comment by kevyonan** [comment]
i believe this is patched as my recent tests have confirmed... for now...
