### ISSUE TITLE
Move Plague Doctor to plugin as a Boss subplugin

### ISSUE THREAD

**Issue by assyrianic** [VSH2-Devs/Vs-Saxton-Hale-2#53]
as a test to show off VSH2's new subplugin system, I'm proposing to move Plague Doctor to a subplugin form instead of having him inside the core plugin itself.

**Comment by assyrianic** [comment]
on hold for now, see #54

**Comment by kevyonan** [comment]
gonna revive this so that the entire forwards system + API can be given code to seriously test.
