### ISSUE TITLE
Enhanced Class/Boss Info Panels

### ISSUE THREAD

**Issue by Starblaster64** [VSH2-Devs/Vs-Saxton-Hale-2#55]
I've been considering this idea for a while, and decided it can't hurt to put it here.

So historically the info panels for class and boss information have been a bit messy, and also restricted by a character limit.

I was thinking that for the class info panels, we could do something like what Custom Weapons 3 does custom weapon info. Split it into weapon slots and passive class abilities (like the optional life regen CVAR), and have a seperate section for the current boss, so you can see what you're fighting against.

Instead of the current message that pops up at the start of a round, a menu will display with your currently equipped weapons and class.
Perhaps as an extra feature add an extra menu that you can use to browse all weapons/classes.

Haven't thought about the boss panels too much, but I guess it could just be set up in 3 categories for boss devs to work with however they want; Weapon(s), abilities, and stats (like if the boss has less HP or multiple lives). Also maybe a bio section, like VSH1 sorta kinda has.
Again, potentially have it be possible to look through all the boss panels of bosses currently in the server with another command.

I don't know if using translation files or leaving in the plugin itself would be more convenient for developers to edit for this, personally not a fan of translation files but it would allow for multi-language support for devs.

I don't know if this would be too much effort for not much gain, but I think the people who do read the class/boss info panels would appreciate it.

**Comment by assyrianic** [comment]
how would that work?

**Comment by Starblaster64** [comment]
Well for the class info panels we can just check for their currently equipped weapons and have them appear as menu options in the popup, along with any innate abilities they have.

**Comment by assyrianic** [comment]
i think the weapon panel should be as is so that players will know what other equipment do.

**Comment by Starblaster64** [comment]
The problem we only have so many characters to work with with the current method. After a certain amount of weapon changes you can't fit all the info in any more.
