### ISSUE TITLE
Bugs with Demoman targe

### ISSUE THREAD

**Issue by x3m77rus** [VSH2-Devs/Vs-Saxton-Hale-2#57]
1. Targe will break on hit even if Demoman under ubercharge.
2. Arrows don't break targe on hit and do damage even if targe is not broken.

Latest dev version.

**Comment by assyrianic** [comment]
makes sense, OnBossDealDamage code shows that uber isn't taken into account.
Arrows do damage because only melee hits are counted.

Perhaps it'd be better and easy for the Shields to only block fatal hits?

**Comment by Starblaster64** [comment]
@assyrianic could be a potential solution. It would stop situations where Bosses deal small amounts of damage and still get your shield (e.g. Easter Bunny). I'm just thinking it might be slightly annoying for Bosses in a handful of scenarios, probably worth it though.

Also, make sure it removes debuffs like bleed/fire so the Demoman doesn't just die right afterwards.

**Comment by kevyonan** [comment]
alright, after a while of laziness. I've managed to patch the shield breaking even while ubered portion. I've also revamped the shield code to block only a fatal hit.
