### ISSUE TITLE
Some sounds not precached

### ISSUE THREAD

**Issue by Starblaster64** [VSH2-Devs/Vs-Saxton-Hale-2#7]
Unsure of what sounds aren't being precached, but my test server console is being spammed with
`SV_StartSound:    not precached (0)` from time to time.

**Comment by assyrianic** [comment]
seems strange. I'll double check the EmitSound functions and see if the sounds are actually precached.

**Comment by Starblaster64** [comment]
Also forgot to mention, I know of at least 1 sound you haven't precached.     `PrecacheSound("items/pumpkin_pickup.wav", true); // Only necessary for servers that don't have halloween holiday mode enabled.`
For the Easter Bunny crit eggs.

**Comment by assyrianic** [comment]
tossing that into code but it's not an .mp3 sound file?

**Comment by Starblaster64** [comment]
I believe mostly only VO soundfiles were converted to MP3 (with some exceptions). I'll double check the file in the VPK now.

**Comment by Starblaster64** [comment]
Yep, still a WAV.

**Comment by Starblaster64** [comment]
Still getting `SV_StartSound:    not precached (0)`
errors.

**Comment by Starblaster64** [comment]
Note to self: Occurs (seemingly) exclusively on round start.

**Comment by kevyonan** [comment]
one sound for HHH was not precached (misc/halloween/spell_teleport.wav), patched it
