### ISSUE TITLE
Use team_round_timer instead of artificial SourceMod timer for Timer_DrawGame

### ISSUE THREAD

**Issue by Starblaster64** [VSH2-Devs/Vs-Saxton-Hale-2#9]
Rather than generate a countdown timer, why not just use the inbuilt timer function? Looks much nicer too, being a part of the actual HUD and all.
You might need to do some extra stuff to get the timer to stop when Hale's HP reaches a certain level though.

**Comment by Starblaster64** [comment]
It would just need to be set up to generate a team_round_timer entity if one doesn't already exist (through tf_arena_round_time), then set the time via ent inputs.

**Comment by assyrianic** [comment]
can definitely be done, this should be a good feature for 1.5+ Beta

**Comment by assyrianic** [comment]
attempted to do this feature but it refuses to work so I left commented out code

**Comment by Starblaster64** [comment]
I also had trouble making it work, I have an idea for a hacky work around though, I'll see if I can make it work this weekend if I have time.

**Comment by assyrianic** [comment]
any luck on this? lol

**Comment by Starblaster64** [comment]
Its moddability is quite limited. For instance, I've been unable to get the AddTime input to work at all, and there's no way to retrieve how much time is remaining on the timer (through netprops).
It should be possible to create a working version specifically as a stalemate timer, but at the same time maybe just enhancing the current custom timer to be more extensible would be a better idea.

**Comment by kevyonan** [comment]
Closing this because the drawgame timer isn't likely to be changed anytime soon in the future as it currently works and does the job.
